# Generated by Django 3.2.20 on 2023-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.IntegerField(blank=True, null=True, verbose_name='создан'),
        ),
    ]
