# Generated by Django 3.2.20 on 2023-08-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20230818_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='адрес')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('prv', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('data', models.DateTimeField(verbose_name='дата')),
                ('publish', models.BooleanField(verbose_name='active')),
                ('count', models.IntegerField(verbose_name='counter')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
