# Generated by Django 3.2.20 on 2023-08-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20230824_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='number')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
