# Generated by Django 3.2.20 on 2023-08-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
