# Generated by Django 3.2.20 on 2023-08-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='cat',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrp', models.CharField(max_length=100, verbose_name='описание')),
                ('created_at', models.IntegerField(blank=True, null=True, verbose_name='создан')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.product')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
